server/applicationPattern/onfModel/constants/OnfPaths.js
server/applicationPattern/onfModel/models/NetworkControlDomain.js
server/controllers/IndividualServices.js
server/database/load.json
server/service/IndividualServicesService.js
server/service/individualServices/PrepareALTForwardingAutomation.js
server/service/individualServices/PrepareForwardingAutomation.js
server/service/individualServices/PrepareForwardingConfiguration.js

Add implementation for the individual service  to include, exclude and list applications

---

server/applicationPattern/databaseDriver/JSONDriver.js
server/applicationPattern/databaseDriver/PrimaryKey.js
server/applicationPattern/onfModel/constants/OnfAttributes.js
server/applicationPattern/onfModel/constants/OnfPaths.js
server/applicationPattern/onfModel/models/NetworkControlDomain.js
server/controllers/IndividualServices.js
server/service/IndividualServicesService.js
server/service/individualServices/PrepareForwardingConfiguration.js

Add implementation for the individual service to support updating LTPs of other applications

---

server/controllers/IndividualServices.js
server/service/IndividualServicesService.js

Add implementation for the individual service  to support updating FCs of other applications

---

server/controllers/IndividualServices.js
server/service/IndividualServicesService.js

Add implementation for the individual service to list the operation servers and clients

---

server/controllers/IndividualServices.js
server/service/IndividualServicesService.js

Add implementation for the individual service  /v1/list-operation-clients-reacting-on-operation-server

---

server/controllers/IndividualServices.js
server/service/IndividualServicesService.js
server/service/individualServices/PrepareForwardingAutomation.js
server/service/individualServices/PrepareForwardingConfiguration.js

Add implementation for the individual service /v1/notify-link-updates

---

server/applicationPattern/onfModel/models/Link.js
server/applicationPattern/onfModel/models/LinkPort.js
server/applicationPattern/onfModel/models/NetworkControlDomain.js
server/applicationPattern/onfModel/services/LinkServices.js
server/controllers/IndividualServices.js
server/service/IndividualServicesService.js
server/service/individualServices/PrepareForwardingAutomation.js

Add implementation for the individual service  to support adding, deleting and listing links

---

server/controllers/IndividualServices.js
server/service/IndividualServicesService.js

Add implementation for the individual service /v1/list-links-to-operation-clients-of-application

---

server/api/openapi.yaml
server/basicServices/AuthorizingService.js
server/basicServices/OamLogService.js
server/controllers/Core.js
server/controllers/HttpClient.js
server/controllers/HttpServer.js
server/controllers/OperationClient.js
server/controllers/OperationServer.js
server/controllers/TcpClient.js
server/controllers/TcpServer.js
server/service/CoreService.js
server/service/HttpClientService.js
server/service/HttpServerService.js
server/service/OperationClientService.js
server/service/OperationServerService.js
server/service/TcpClientService.js
server/service/TcpServerService.js

Add OAM services implementation

---

server/database/load.json
server/dockerfile
server/index.js
server/service/IndividualServicesService.js

Add docker file to create docker image

---

server/service/IndividualServicesService.js

Modify the response body of /v1/list-end-points-of-link

---

server/controllers/OperationClient.js
server/controllers/OperationServer.js
server/controllers/TcpClient.js
server/controllers/TcpServer.js

PUT operations in OAM layer should return 204 (Implementation)

---

server/service/IndividualServicesService.js

/v1/list-applications : implementation to be changed

---

server/controllers/IndividualServices.js

server : /v1/list-applications - include headers in response

---

server/service/IndividualServicesService.js

server : /v1/delete-fc-port : update need for handling exception

---

server/applicationPattern/commons/AppCommons.js
server/applicationPattern/onfModel/services/ForwardingConstructAutomationServices.js
server/applicationPattern/rest/client/eventDispatcher.js
server/applicationPattern/services/AuthorizingService.js
server/applicationPattern/services/ExecutionAndTraceService.js
server/applicationPattern/services/OamLogService.js
server/controllers/BasicServices.js
server/controllers/Core.js
server/controllers/HttpClient.js
server/controllers/HttpServer.js
server/controllers/IndividualServices.js
server/controllers/OperationClient.js
server/controllers/OperationServer.js
server/controllers/TcpClient.js
server/controllers/TcpServer.js
server/index.js
server/package-lock.json
server/service/individualServices/SoftwareUpgrade.js

- files synced from AP: 
eventDispatcher.js
AuthorizingService.js
ExecutionAndTraceService.js
OamLogService.js
- fixed typos in BasicServices.js
- validate api-key auth and basic auth via oas3-tools framework: 
index.js
AppCommons.js
Core.js
HttpClient.js
HttpServer.js
OperationClient.js
OperationServer.js
TcpClient.js
TcpServer.js
- fixed all imports and code according to changes mentioned above
Fixes https://github.com/openBackhaul/ApplicationPattern/issues/123 
Fixes https://github.com/openBackhaul/ApplicationLayerTopology/issues/47
Signed-off-by: Martin Sunal <martin.sunal@paxet.io>

Refactored security validators

---

ApplicationLayerTopology_0.0.2_tsi.220110.1955+data.2.json

userName attribute add to data file, and syntax error at line 811

---

server/applicationPattern/onfModel/services/LinkServices.js

Fixes https://github.com/openBackhaul/ApplicationLayerTopology/issues/97

Fix : When we trigger /v1/add-operation-client-to-link service with new link details , forwarding /v1/regard-update-link to OKM is returning 400

---

ApplicationLayerTopology+config.json
ApplicationLayerTopology.yaml

Updating the UUIDs of FCs

---

ApplicationLayerTopology+config.json
ApplicationLayerTopology+profileInstances.yaml
ApplicationLayerTopology+profiles.yaml
ApplicationLayerTopology.yaml

Minimizing the ActionProfile

---

ApplicationLayerTopology.yaml

Change reference of subscriber-operation to server

---

ApplicationLayerTopology+config.json
ApplicationLayerTopology+services.yaml

Add protocol attribute at TcpServer and TcpClient

---

ApplicationLayerTopology.yaml

Add uuid patterns in RequestBodies

---

ApplicationLayerTopology+config.json
ApplicationLayerTopology+profileInstances.yaml
ApplicationLayerTopology+services.yaml
ApplicationLayerTopology.yaml

Remove ApiSegment from UUIDs of HttpClients/Servers and TcpClients/Servers

---

ApplicationLayerTopology+config.json
ApplicationLayerTopology+forwardings.yaml
ApplicationLayerTopology+services.yaml
ApplicationLayerTopology.yaml

Fixes #194
Fixes #192
Fixes #196

Add forwardings to initiate requests to OKM

---

spec/ApplicationLayerTopology+config.json
spec/ApplicationLayerTopology+forwardings.yaml
spec/ApplicationLayerTopology+services.yaml
spec/ApplicationLayerTopology.yaml

Change sequence number of /v1/notify-link-updates

---

server/service/IndividualServicesService.js
server/service/individualServices/PrepareForwardingConfiguration.js

issue-66 : remove callback from regard-application

---

server/service/IndividualServicesService.js

Resolved Support Version 2.0.0 changes for list-application

---

server/controllers/ElasticsearchClient.js
server/database/load.json
server/index.js
server/package-lock.json
server/package.json
server/service/ElasticsearchClientService.js
server/service/individualServices/ElasticsearchPreparation.js

Links mapping has to be determined.

issue-239 : added Elasticsearch and proper mapping for control-construct

---

server/applicationPattern/onfModel/services/ForwardingConstructAutomationServices.js
server/service/IndividualServicesService.js

Fixes #205.
Tied to (PR 576)[https://github.com/openBackhaul/ApplicationPattern/pull/576]

issue-205 : record callback response to ES

---

server/controllers/IndividualServices.js
server/service/IndividualServicesService.js

- simplified handling
Fixes #209

issue-209 : update ltps and fcs to ES

---

server/service/IndividualServicesService.js

Resolved Support Version 2.0.0 changes for disregard-application

---

server/controllers/ActionProfile.js
server/controllers/Core.js
server/controllers/GenericResponseProfile.js
server/controllers/HttpClient.js
server/controllers/HttpServer.js
server/controllers/OperationClient.js
server/controllers/OperationServer.js
server/controllers/TcpClient.js
server/controllers/TcpServer.js
server/service/ActionProfileService.js
server/service/CoreService.js
server/service/GenericResponseProfileService.js
server/service/HttpClientService.js
server/service/HttpServerService.js
server/service/OperationClientService.js
server/service/OperationServerService.js
server/service/TcpClientService.js
server/service/TcpServerService.js
server/service/individualServices/PrepareForwardingAutomation.js

Resolved Implement OAM Services for version 2.0.0

---

server/service/IndividualServicesService.js
server/service/individualServices/individualServicesOperationsMappingnotify.js

Resolved Support Version 2.0.0 changes for /v1/notify-link-updates

---

server/service/IndividualServicesService.js

issue-193 : create links for regarded applications operation server

---

server/service/IndividualServicesService.js

Support Version 2.0.0 changes for /v1/list-end-points-of-link

---

server/service/IndividualServicesService.js

Support Version 2.0.0 changes for /v1/list-operation-client-at-application

---

server/service/IndividualServicesService.js

Support Version 2.0.0 changes for /v1/list-operation-servers-at-application

---

server/service/IndividualServicesService.js
server/service/individualServices/ControlConstructService.js
server/service/individualServices/LinkServices.js
server/service/individualServices/PrepareForwardingAutomation.js
server/service/individualServices/SoftwareUpgrade.js
server/service/models/Link.js
server/service/models/LinkPort.js

- Renamed NetworkControlDomain to ControlConstructService
- updated imports

Moved relevant files from local applicationPattern

---

server/service/individualServices/IndividualServicesOperationsMapping.js

Resolved Include uuid syntax for the subscriber-operation attribute for the service /v1/notify-link-updates

---

server/service/IndividualServicesService.js
server/service/individualServices/ForwardingService.js

Support Version 2.0.0 changes for update-fc

---

server/index.js
server/package.json
server/service/IndividualServicesService.js
server/service/individualServices/ForwardingService.js
server/service/individualServices/PrepareForwardingConfiguration.js

Fixes #215
In addition ,
Updated latest npm packages
Corrected the imports in index and PrepareForwardingConfiguration files

Support Version 2.0.0 changes for update-fc-port

---

server/service/IndividualServicesService.js
server/service/individualServices/ForwardingService.js

Support Version 2.0.0 changes for delete-fc-port

---

server/controllers/IndividualServices.js
server/service/IndividualServicesService.js
server/service/individualServices/ControlConstructService.js
server/service/individualServices/ElasticsearchPreparation.js
server/service/individualServices/LinkServices.js
server/service/individualServices/PrepareForwardingAutomation.js

issue-195 : implementation of update-ltp with forwardings

---

server/service/IndividualServicesService.js
server/service/individualServices/ControlConstructService.js

Update services "Application existence check" needs to be updated

---

server/package-lock.json
server/package.json
server/service/IndividualServicesService.js
server/service/individualServices/ControlConstructService.js
server/service/individualServices/LinkServices.js
server/service/models/Link.js

Fixes #219
Fixes Support Version 2.0.0 changes for /v1/remove-operation-client-from-link #220
Fixes generate links UUID using a library #265

Support Version 2.0.0 changes for /v1/add-operation-client-to-link

---

server/service/IndividualServicesService.js

Resolve while executing /v1/update-all-ltps-and-fcs getting 500 Internal Server Error

---

server/controllers/BasicServices.js

 Resolve while executing informAboutApplicationInGenericRepresentation and informAboutReleaseHistoryInGenericRepresentation are giving empty list

---

server/controllers/IndividualServices.js
server/service/IndividualServicesService.js
server/service/individualServices/ControlConstructService.js
server/service/individualServices/ForwardingService.js
server/service/individualServices/LinkServices.js
server/service/models/Link.js

Other methods will be added in another merge request to avoid huge changes.
#297

Issue 297 : added backendTime

---

server/service/models/Link.js
server/service/models/LinkPort.js

Services communicating to Elastic search responds 500 Internal server error

---

README.md
doc/ElasticsearchUsage.md
doc/main.md

Documentation for Elasticsearch usage in ALT

---

server/service/IndividualServicesService.js
server/service/individualServices/SoftwareUpgrade.js

Resolve correct the tcpserverInterface  in bequeathYourDataAndDie and include the toString() method

---

server/controllers/IndividualServices.js
server/service/IndividualServicesService.js
server/service/individualServices/ControlConstructService.js
server/service/individualServices/LinkServices.js

Issue 297 - added backend parameters to list methods

---

server/service/IndividualServicesService.js
server/service/individualServices/ControlConstructService.js
server/service/individualServices/PrepareForwardingAutomation.js

issue-325 : make requests idempotent

---

server/service/IndividualServicesService.js
server/service/individualServices/ControlConstructService.js
server/service/individualServices/LinkServices.js
server/service/individualServices/PrepareForwardingAutomation.js

issue-297 : add backend time to ControlConstruct

---

server/package-lock.json
server/package.json

issue-340 : switch to AP 2.0.1-alpha.12

---

server/service/IndividualServicesService.js
server/service/individualServices/SoftwareUpgrade.js

resolve Proposal to use the 'getAllApplicationList' method to from ApplicationPattern

---

server/service/IndividualServicesService.js
server/service/individualServices/ControlConstructService.js
server/service/individualServices/ForwardingService.js
server/service/individualServices/LinkServices.js
server/service/individualServices/PrepareForwardingAutomation.js

- some refactoring before the actual change, see commits

issue-319 : preparation

---

server/service/IndividualServicesService.js
server/service/individualServices/ControlConstructService.js
server/service/individualServices/ForwardingService.js

issue-349 : fixed delete-ltp-and-dependants

---

server/service/IndividualServicesService.js

issue-348 : fixed a few bugs related to regard-application

---

server/service/individualServices/ControlConstructService.js
server/service/individualServices/LinkServices.js
server/service/models/Link.js
server/service/models/LinkPort.js

- removal of unused methods
Relates to #297

issue-297 : simplified link handling

---

server/service/IndividualServicesService.js
server/service/individualServices/ForwardingAutomationServiceWithResponse.js
server/service/individualServices/SoftwareUpgrade.js

issue-348 : new Service allows to wait for one callback

---

server/dockerfile
server/package-lock.json

Update dockerfile with "npm ci --only=production"

---

server/service/IndividualServicesService.js
server/service/individualServices/SoftwareUpgrade.js

 resolve change the method name from resolveHttpTcpAndOperationClientUuidFromForwardingName in the bequeathyourdataanddie service

---

server/service/individualServices/ForwardingService.js

issue-333 : fix version conflicts

---

server/service/IndividualServicesService.js
server/service/individualServices/SoftwareUpgrade.js

issue-360 : fixed trace-indicator

---

server/service/IndividualServicesService.js

update-ltp should not return an error if the LTP is not in ES, it should add it.
Fixes #395

issue-395 : fix error handling

---

server/service/IndividualServicesService.js

issue-358 : moved check for own application

---

server/controllers/BasicServices.js

issue-390 : header values taken from headers

---

server/controllers/BasicServices.js
server/service/IndividualServicesService.js

Fix releated to AP#736

---

server/service/IndividualServicesService.js
server/service/individualServices/ForwardingAutomationServiceWithResponse.js
server/service/individualServices/LinkServices.js

regard-application is not working for scenario if provided ip address is not reachable.

---

server/service/models/Link.js

issue-409 : fixed missing refresh param

---

server/database/load.json

In server/load.json, CurrentController data shall be removed

---

server/service/individualServices/PrepareForwardingAutomation.js

disregard-application should call delete-ltp-and-dependants

---

server/service/IndividualServicesService.js
server/service/individualServices/LinkServices.js

issue-414 : fixed link creation

---

server/index.js
server/service/individualServices/LinkServices.js
server/utils/preApprovedLinks.json

Including preapproved links to the application data

---

server/service/individualServices/LinkServices.js

link-port without logical-termination-points are getting created for regarded application

---

server/service/IndividualServicesService.js
server/service/individualServices/ControlConstructService.js

Improvements to delete-ltp and update-ltp

---

server/service/individualServices/SoftwareUpgrade.js

resolve The request-body formulation for callback bequeath-your-data-and-die should be modified

---

server/service/individualServices/ForwardingAutomationServiceWithResponse.js

issue-402 : ALT expects HTTP error 408 when callback is not successful

---

server/service/individualServices/LinkServices.js

To resolve the getLinkOfTheOperationAsync export issue in LinkServices

---

server/database/load.json

alt-2-0-1-op-s-is-022 to be added to INPUT fc-port of ServiceRequestCausesLtpUpdateRequest and ServiceRequestCausesFcUpdateRequest

---

server/controllers/IndividualServices.js
server/service/IndividualServicesService.js

Update-ltp is returning 500 because of the undefined operationServer

---

server/service/individualServices/PrepareForwardingAutomation.js

/v1/update-ltp is failing with Internal Server Error if we are updating operation client uuid

---

server/service/IndividualServicesService.js

Resolve /v1/bequeath-your-data-and-die is not sending a notification to /v1/update-ltp for tcp-client and hhtp-client  Updation

---

server/service/individualServices/LinkServices.js

creating pre-approved links should create links in output-input order

---

server/index.js
server/service/individualServices/ElasticsearchPreparation.js

- also disabled automatic creation of indices
Fixes #464

issue-464 : ES should be configured before http server

---

server/service/IndividualServicesService.js
server/service/individualServices/LinkServices.js
server/service/individualServices/PrepareApprovedLinks.js
server/service/individualServices/PrepareForwardingAutomation.js

issue-436 : send forwardings for link change in regard-application

---

spec/ApplicationLayerTopology.yaml

Change LinkUuid and pattern (fixes #286)

---

testing/ApplicationLayerTopology+data.json

resolve need to correct the Elastic-search validation for /V1/LIST-LTPS-AND-FCS and /V1/REDIRECT-TOPOLOGY-CHANGE-INFORMATION

---

spec/ApplicationLayerTopology.yaml

Correct uuid to new format (fixes #301)

---

spec/ApplicationLayerTopology+config.json
spec/ApplicationLayerTopology+forwardings.yaml

Add /v1/notify-link-updates to 2 forwardings

---

testing/ApplicationLayerTopology+data.json

resolve Testsuite adjustments

---

server/service/IndividualServicesService.js

issue-482 : new param for createOrUpdateApplicationLtpsAsync

---

spec/ApplicationLayerTopology+config.json
spec/ApplicationLayerTopology+profileInstances.yaml

Include Response Profiles for new releases (fixes #556)

---

spec/ApplicationLayerTopology.yaml

Update ResponseCode in PromptForBequeathingDataCausesTransferOfListOfApplications (fixes #532)

---

server/controllers/BasicServices.js

Fixes
https://github.com/openBackhaul/ApplicationLayerTopology/issues/581
Reviewer @PrathibaJee

Handled ALT's register-yourself forwarding PromptForEmbeddingInitiatesEmbeddingProcess.RequestForBequeathingData

---

server/service/individualServices/regardApplicationAutomation.js

Fixes https://github.com/openBackhaul/ApplicationLayerTopology/issues/580
Reviewer @PrathibaJee @IswaryaaS

Optimized logic for checking response status code in API /v1/regard-application

---

server/service/individualServices/SoftwareUpgrade.js

Fixes https://github.com/openBackhaul/ApplicationLayerTopology/issues/585
reviewer @PrathibaJee @IswaryaaS

Modified the implementation of callback PromptForBequeathingDataCausesTransferOfListOfApplications

---

server/api/openapi.yaml
server/controllers/BasicServices.js
server/controllers/IndividualServices.js
server/controllers/IntegerProfile.js
server/package-lock.json
server/service/IntegerProfileService.js
server/service/individualServices/regardApplicationAutomation.js

undo commit  'Merge branch 'develop' into v2.1.2_impl'

---

server/service/individualServices/ControlConstructService.js

Fix: https://github.com/openBackhaul/ApplicationLayerTopology/issues/595
@PrathibaJee

Resolved ESlint problem 
